// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['api_key'] ?? 'default_api_key',
    appId: dotenv.env['app_id'] ?? 'default_app_id',
    messagingSenderId: dotenv.env['messaging_sender_id'] ?? 'default_messaging_sender_id',
    projectId: dotenv.env['project_id'] ?? 'default_project_id',
    storageBucket: dotenv.env['storage_bucket'] ?? 'default_storage_bucket',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['api_key'] ?? 'default_api_key',
    appId: dotenv.env['app_id'] ?? 'default_app_id',
    messagingSenderId: dotenv.env['messaging_sender_id'] ?? 'default_messaging_sender_id',
    projectId: dotenv.env['project_id'] ?? 'default_project_id',
    storageBucket: dotenv.env['storage_bucket'] ?? 'default_storage_bucket',
    iosBundleId: dotenv.env['ios_bundle_id'] ?? 'default_ios_bundle_id',
  );
}
